### ISSUE TITLE
Proper error handling application wide

### ISSUE THREAD

**Issue by dema-trading-ai** [dema-trading-ai/engine#10]
In the current implementation, alot of SystemExits are raised when an error occured. This is done on purpose, but will not serve our future goal of making everything maintainable. 

For example:
````python
  print("[ERROR] Backtesting datafile was not found.")
  raise SystemExit
````

Should be replaced with:
````python
    raise FileNotFoundError("[ERROR] Backtesting datafile was not found.")
````

**Comment by marijn111** [comment]
@deborahvans How is this issue going? Did you managed to make progress? Let me know if you need help!
