### ISSUE TITLE
[Docs] Write content for 'Making Money'

### ISSUE THREAD

**Issue by dema-trading-ai** [dema-trading-ai/engine#105]
For the BETA version, it is necessary that the **Making money** part is filled with appropriate information. We need proper calculations and a step-by-step guide of how the process will go when you want your strategy published.

**Comment by dema-trading-ai** [comment]
@WesleyvanDooren would you mind picking up this issue?

**Comment by keebrev** [comment]
Things to mention:
1. First some strategy development (see other documentation issue #106 )
2. Having a nice working algorithm
3. DemaTrading optimizing the algorithms
4. DemaTrading exporting / publishing the algorithm
