### ISSUE TITLE
[Docs] Strategy example / getting started additions

### ISSUE THREAD

**Issue by dema-trading-ai** [dema-trading-ai/engine#106]
We need a step-by-step guide of how to create your first own algorithm. This need to be done in docs part **strategy examples**

**Comment by dema-trading-ai** [comment]
@noudcorten could you maybe pick up this issue?

**Comment by keebrev** [comment]
@noudcorten Roughly the steps that should be explained: 

1. Play with Technical Indicators on TradingView
2. Find nice Technical Indicators
3. Look at for available indicators in TA-lib http://mrjbq7.github.io/ta-lib/funcs.html
4. Implement indicators in indicator method
5. Implement populated indicators in buy / sell signal
