### ISSUE TITLE
Add a proper CLI

### ISSUE THREAD

**Issue by pvdklei** [dema-trading-ai/engine#120]
Currently, to run the engine you either have to do the docker commands `docker build ....` and `docker run ....`, or use `make` which isn't really made for this. We still need to configure `docker-compose` but the commands would still be long does not look really authentic. What do you think about making an executable that handles this?

`$dema run` and `$dema build`

**Comment by marijn111** [comment]
@pvdklei #130 adds docker-compose configuration. it allows for custom commands (with `run`, including optional arguments), but also the default (most used?) command with just `up`. Should improve things a little
