### ISSUE TITLE
[Bug] fix bug when downloading data

### ISSUE THREAD

**Issue by dema-trading-ai** [dema-trading-ai/engine#123]
Have a look at the screenshot.
<img width="622" alt="screenshot" src="https://user-images.githubusercontent.com/79081253/112889276-b7bd4380-90d5-11eb-8528-53c36b136aee.png">

**Comment by pvdklei** [comment]
How can I replicate this bug?

**Comment by keebrev** [comment]
@pvdklei 
1. Run a backtest with setting 'backtesting_till_now' = 'False'
2. Now run a backtest with same setting on 'True'
3. Wait 5m (or 1 tick for specified timeframe). Do this again, you'll see the error.
