### ISSUE TITLE
[Feat] Progress bar

### ISSUE THREAD

**Issue by noudcorten** [dema-trading-ai/engine#134]
@DemianVoorhagen6 suggested to implement a progress bar. When strategies become more complicated, progress bars are becomming really important to visualize how long the backtest is going to take

Things to do:
* Implement progress bar

**Comment by pvdklei** [comment]
Didn't we already have one? It's just been removed because backtesting is so fast now you cannot see the progress bar anymore

**Comment by noudcorten** [comment]
@pvdklei Yes, but since backtesting has now become extremely fast I removed it in #131 . But after some talks with @dema-trading-ai we decided to put them back in.
