### ISSUE TITLE
Make custom stoploss method work with current implementation

### ISSUE THREAD

**Issue by keebrev** [dema-trading-ai/engine#147]
After the adjustments for overall backtesting speed, the implementation on Custom StopLoss function in the strategy.py file has not been implemented correctly. This currently overrides stoploss for ALL trades, while we actually want it to set a custom stoploss for EVERY trade. 

Please get in touch with Tijs if things are unclear. 
 
Things to do:
- Revise tradingmodule.py line 87/88 (open_trade_tick)
- Revise backtesting.py line 88/89 (populate_indicators)
- Make sure the Stoploss is put into data_dict in backtesting.py (start_backtesting)
- Revise tradingmodule.py method check_stoploss_open_trade to start using either custom stoploss if set, else use configured SL from config.

**Comment by keebrev** [comment]
@noudcorten something you would like to do?

**Comment by noudcorten** [comment]
@keebrev yes I can take this one.

**Comment by noudcorten** [comment]
Fixed in #146. Closing.
