### ISSUE TITLE
OHLCV data / indicators to DataFrame

### ISSUE THREAD

**Issue by keebrev** [dema-trading-ai/engine#18]
**(Together with Tijs)**

Currently, all our OHLCV data and indicators are stored in either an object array or dictionary. This is not really useful for TA-Lib / calculating purposes (since TA-Lib requires numpy array as input). We need to put all data inside a dataframe, and make this work application-wide. This is necessary for the strategies to work.

**Comment by marijn111** [comment]
Issue fixed through #43, closing
