### ISSUE TITLE
Proper startup time

### ISSUE THREAD

**Issue by keebrev** [dema-trading-ai/engine#23]
Because some indicators are calculated based on x amount of passed candles (f.e. SMA), we need a startup time to be able to generate the indicators properly.

Things to be done:
- Make startup time
- Check for presence in config file
- During the first x candles, send no signals / generate no indicators

Addition: if there's any possibility to find the appropriate startup time automatically, this would be perfect!

**Comment by marijn111** [comment]
> * During the first x candles, send no signals / generate no indicators

This is not correct. The indicators SHOULD be generated during the startup time. However, during the startup time they are not 'valid', i.e. no buy/sell signals should be produced indeed. 

After the startup time, the indicators are valid and can be 'used'. If you start generating the indicators only after the startup time you run into the exact same problem. 

@WillemGerritzen Let me know if things are unclear

**Comment by marijn111** [comment]
Done. Closing.
