### ISSUE TITLE
Check if used timestamps are correct

### ISSUE THREAD

**Issue by noudcorten** [dema-trading-ai/engine#268]
The engine makes use of timestamps.
The timestamps are downloaded using the binance.fetch function, but it is unsure which time configuration is used here.
We need to research if there are possible conflicts in using this function in different timezones.
Also, we need to find out if datetime.fromtimestamp and datetime.timestamp handle miliseconds the same way (see tradingmodule.py)

**Comment by sheridavandenbent** [comment]
timestamps are used consistently with milliseconds throughout the engine. Timezone is a bit more difficult and not that impactful at the moment. Will be more impactful when we're dealing with more than one exchange. Let's look at it again, then.  Closing the issue for now.
