### ISSUE TITLE
Add multi timeframe support

### ISSUE THREAD

**Issue by dema-trading-ai** [dema-trading-ai/engine#47]
Create a way to be able to use multiple timeframes for every pair.

Things to be done:
- Make it easy configurable
- Adjust downloading / checking for multiple timeframes
- Make data easy accessible in generate_indicators methods

**Comment by noudcorten** [comment]
For this to be possible we should change the index of our dataframe to DatetimeIndex first.

**Comment by dema-trading-ai** [comment]
Alright. I see you've been busy doing this. Should I assign you? @noudcorten

**Comment by noudcorten** [comment]
@dema-trading-ai 
> Alright. I see you've been busy doing this. Should I assign you? @noudcorten

Yes sure.
