### ISSUE TITLE
Add marketchange (avg + bitcoin)

### ISSUE THREAD

**Issue by keebrev** [dema-trading-ai/engine#61]
We want to know the average marketchange for whitelisted coins in set backtesting period. 

Things to do:
- Make calculations for average marketchange for all whitelisted coins (printed %)
- Make calculations for average marketchange for bitcoin (as benchmark) (printed %)
- Include results in backtesting overview

**Comment by marijn111** [comment]
@UdristeAndrei How is it going with this issue? Do you need help?
