### ISSUE TITLE
Enhancement - add fee support

### ISSUE THREAD

**Issue by pvdklei** [dema-trading-ai/engine#63]
Currently, fees are excluded from all calculations. Things that must be done include: 

- Determine whether the fee  in `config.json` must be a percentage or fraction? Or can be both, and percentage is specified by typing for instance `fee: "0.1%"`
- Come up with suitable validations for the provided fee value (e.g., must be positive, less than 1 or 100%)
- Fees must be included in budget changes in `Tradingmodule.open_trade()` and `.close_trade()`.
- Save fee statistics like `total_fee_paid` in `TradingModule`, and print them in the final results (`BackTesting`).

**Comment by keebrev** [comment]
@pvdklei I think this is a valid question, although I don't think you want to include the % sign in the config files.

**Comment by pvdklei** [comment]
> @pvdklei I think this is a valid question, although I don't think you want to include the % sign in the config files.

Yeah, I don't think that would be too nice either
