### ISSUE TITLE
Bug - progress bar on above other notifications 

### ISSUE THREAD

**Issue by pvdklei** [dema-trading-ai/engine#67]
For most people this seems to work, but on my m1 mac, using MacOS Bug Sur (in a zsh shell) there is a small bug in the progress bar. The progress bar should go above the info tags, but for me the progress bar is shown first, and then the other `print`s come. We are supposed to see: 

![suppos](https://user-images.githubusercontent.com/54803002/109948268-71451680-7cda-11eb-804b-34d12500d70d.png)

But I get: 

<img width="576" alt="Screenshot 2021-03-03 at 17 37 18" src="https://user-images.githubusercontent.com/54803002/109948302-7b671500-7cda-11eb-9243-8c87c5b93908.png">

**Comment by keebrev** [comment]
@pvdklei Is it an idea to quit using zsh? 🤣  Moreover, after todays update the backtest time will decrease 240%.

**Comment by pvdklei** [comment]
@keebrev hahahah thats always a good idea. But found out that it has something to do with docker this time. I noticed! No wait times any more, so illl close the issue.
