### ISSUE TITLE
Command line argument support

### ISSUE THREAD

**Issue by noudcorten** [dema-trading-ai/engine#69]
If we want to change a variable we currently have to edit the config.json, which is a bit devious. Therefore it is nice to add command line support to easily change the variables or select a different strategy.

Things to do:
* Make every argument in the config.json configurable using the command line.
* Add --help argument to see which variables can be changed

**Comment by keebrev** [comment]
I like the idea, however, I do not think we need to be able to configure EVERYTHING using the commandline. I suggest we make a list of items that are configurable using commandline.

**Comment by pvdklei** [comment]
@keebrev Maybe we should then make a config specification, so we can easily add params or indicate whether it should be changeable using the command line. I mean something like: 

```
{
  "exchange": {                 // the specification for the 'exchange' param
    "cli": { 
      "help": "To change the exchange", // shown when --help is passed
      "short": "exc"           // so you can use it with '-exc' instead of '--exchange'
    }, 
    "default": "binance",      // if no default is given, it is required
    "options": ["binance"]     // if someone gives a wrong exchange, we can kindly give them a list of whats possible
  },
  "strategies-folder": {       // here, cli is not given, so it cant be altered using the command line
    "default": "strategies"
  }
}
```
We could add much more, like a `description` for every param. Let me know what you think.

**Comment by marijn111** [comment]
Done. Closing.
