### ISSUE TITLE
Research for Hyper Optimization possibilities

### ISSUE THREAD

**Issue by dema-trading-ai** [dema-trading-ai/engine#72]
In the upcoming months, we really want to implement HyperOpting in our backtesting engine. For this, we need to know what needs to be changed concerning the current implementation.

Things to check out:
- What of the current implementation should be changed to match requirements for hyperopting
- How long would it take to implement hyperopting
- What separate tasks could be made for hyperopt implementation? + task time estimation

**Comment by pvdklei** [comment]
I think we first need to do something with #104. Currently every time you backtest it takes about half a minute, hyperoptimizing would take ages with this performance.

**Comment by geordle** [comment]
Implemented in #352.
