### ISSUE TITLE
Plotting possibilities after running backtest

### ISSUE THREAD

**Issue by dema-trading-ai** [dema-trading-ai/engine#73]
A nice addition would be some kind of plots to visualize the following things after/during backtesting:
- Budget over time
- Buy/Sell moments on price graph of certain coin pair (OHLCV)
- Average profit of trades over time
- ... <insert additions here>

What do you guys think?
What should be changed on current implementation to match requirements for plotting?

**Comment by noudcorten** [comment]
This would be a really nice feature I think. Only problem with our current implementation is that some of this information (e.g. 'buy' and 'sell' signals) are not stored and only used once. Furthermore, I have no idea if the plot is going to look nice and clean. I found this (https://towardsdatascience.com/trading-toolbox-03-ohlc-charts-95b48bb9d748) which I think is not that hard to implement and a nice first issue to try out.

**Comment by keebrev** [comment]
Yup! This could only be implemented with your new suggestion of our backtesting flow. Other opensource projects use plotly for plotting. Have a look at that as well :). Make sure to think about this when implementing #104

**Comment by deborahvans** [comment]
These  plots are even easier to make: https://plotly.com/python/ohlc-charts/

They look pretty neat 
<img width="1239" alt="image" src="https://user-images.githubusercontent.com/71016477/114079089-058e3480-98aa-11eb-96df-e42836d4ef87.png">

You can even zoom in 
<img width="1230" alt="image" src="https://user-images.githubusercontent.com/71016477/114079175-26568a00-98aa-11eb-850b-2e9a5be5ea03.png">

But maybe there should be less data point for a clear overview?

**Comment by keebrev** [comment]
@deborahvans it looks pretty neat indeed. Do we also have possibilities to add other things to the graph like EMA/SMA or something like that?

**Comment by deborahvans** [comment]
As long as we have the formula we can add anything we want :)

<img width="1247" alt="image" src="https://user-images.githubusercontent.com/71016477/114153635-d1edf180-991f-11eb-910e-c0baefa0a429.png">
