### ISSUE TITLE
Dynamic stoploss for every trade

### ISSUE THREAD

**Issue by dema-trading-ai** [dema-trading-ai/engine#75]
We have to have to ability to configure stoploss (SL) on a per trade basis. This allows for configuring stoplosses on the go, based on indicators for example. This should be an option for more advanced users. 
The config should have the standard 'static' stoploss, which gets overridden in case a user specifies it when opening a trade. 

Things to do:
- Create method in strategy base class, method should return stoploss (float) for every new trade
- Baseclass method always returns config default SL
- Create SL calculation method in strategy, so it's configurable for every trade that opens + for every strategy
- Call SL calculation method on opening trade. Store SL in trade model
- Add property to trade model for storing trade specific SL
- Adjust methods in trading module for working with trade specific SL when this is turned on

**Comment by marijn111** [comment]
@WesleyvanDooren Could you keep an eye out for this, and put it in the wiki once it is implemented? Thanks!

**Comment by WesleyvanDooren** [comment]
I didn't get the comment notification, however, of course!
