### ISSUE TITLE
Revise Makefile so volume mounting works

### ISSUE THREAD

**Issue by dema-trading-ai** [dema-trading-ai/engine#89]
Currently, in the makefile we have a section for 'runv', which should mount the current directory to the container of the engine. This is done so downloaded data could be re-used. However, this doesn't seem to work.

This is no priority, only an addition. We should be better off by using a **docker-compose file.** Docker-compose HAS priority.

**Comment by WesleyvanDooren** [comment]
runv: 
	docker run --rm -it -v $(PWD):/dema-engine:alpha -w /dema-engine:alpha dockerImage bash
	
Wouldn't this line be better?
